### PR TITLE
Fixed a spout small typo error

### PR DESCRIPTION
**Pull request by vshlapakov**
Check it, please. Also something is wrong with last changes in `master` branch, even `wordcount` topology hangs for me now, w/o any errors, could you check it too please? I'll investigate it deeper and open an issue if I find something interesting.

### CODE REVIEW

**Comment by dan-blanchard** [comment]
Wow, thanks for catching this.  Definitely need spout tests. (Hence the bad coverage number we have right now).

**Comment by vshlapakov** [comment]
Yeah, definitely, thanks for the quick merge!

**Comment by dan-blanchard** [comment]
I'll put more tests together today and figure out what's going on.  Thanks for bringing this to my attention!

**Comment by dan-blanchard** [comment]
I've added some basic spout tests, and all of them pass now.  There were a few more missing `self.` prefixes in that file after a major reorg.

**Pull request merged**
