### PR TITLE
Fix permissions when env user cannot be used for ssh login

### PR DESCRIPTION
**Pull request by dan-blanchard**
This PR makes it possible for you to use your own user account as the SSH login account for a server and then sudo to a different user for creating virtualenvs. This handles the common scenario where the superuser that you need to use to write the virtualenv is not a login account.

### CODE REVIEW

**Comment by emmett9001** [comment]
Is there anything blocking the merge of this PR?

**Comment by dan-blanchard** [comment]
It needs to be expanded upon for backward compatibility. I was planning on adding new settings so you can specify the user that the virtualenv creation/deletion commands run as independently of the SSH user.

**Comment by emmett9001** [comment]
I'm happy to make the remaining necessary changes here if you can convey some more specific idea of what's left to be done, @dan-blanchard.

**Comment by dan-blanchard** [comment]
I can add it just as quickly as I could explain it, so I'll just bang it out.

**Pull request merged**
