### PR TITLE
[WIP] switch to parallel-ssh from fabric 

### PR DESCRIPTION
**Pull request by tanaysoni**
Issue: https://github.com/Parsely/streamparse/issues/394

### CODE REVIEW

**Comment by tanaysoni** [comment]
@dan-blanchard I've taken a first stab just for the `_create_or_update_virtualenv()`. I'm looking forward to your feedback.

**Comment by tanaysoni** [comment]
@dan-blanchard I have removed fabric as a dependency and all the CLI commands seemingly work on my local.

The Travis build for PyPy is failing, which I suspect is due to `parallel-ssh` not being compatible with PyPy. What could be a workaround for that? 

There are some dangling fabric references in variable names and comments that needs to be cleaned up. Besides that, please let me know if there's anything that I might have missed out.

**Comment by tanaysoni** [comment]
Hi @dan-blanchard, wondering if you got a chance to look at it?

**Comment by codywilbourn** [comment]
I looked in to why the PyPy failures were occurring and it was due to being unable to find the libssh2.h

```
cc -O2 -fPIC -Wimplicit -Ilibssh2/include -I/home/travis/virtualenv/pypy-5.4.1/include -c pssh/native/ssh2.c -o build/temp.linux-x86_64-2.7/pssh/native/ssh2.o -O3
  pssh/native/ssh2.c:522:21: fatal error: libssh2.h: No such file or directory
```

It was searching in `libssh2/include` and `/home/travis/virtualenv/pypy-5.4.1/include` for that file, but was unable to find it. I couldn't determine how this `libssh2.h` is provided -- would pypi have to install it separately, or is it supposed to be part of the `parallel-ssh` installation itself? In that case, why wasn't it in either of the two directories? Maybe @dan-blanchard has some ideas, I'm not familiar with pypy.

**Comment by dan-blanchard** [comment]
@codywilbourn The issue is that for the other platforms we're installing a manylinux wheel that is statically linked to libssh2. We need to update `.travis.yml` to include libssh2 for our PyPy build. I can do that.

**Comment by dan-blanchard** [comment]
Thanks so much for all your work @tanaysoni. I'll push this the rest of the way over the finish line in #411.

**Pull request closed without merging**
